### ISSUE TITLE
yolov8n-seg.onnx int8 conversion problems encountered(yolov8 seg int8遇到的问题)

### ISSUE THREAD

**Issue by LijialinHub** [jws92/YOLOv8-TensorRT#2]
[05/11/2024-09:13:04] [TRT] [E] 10: Could not find any implementation for node Conv_74 + PWN(PWN(Sigmoid_75), Mul_76).
[05/11/2024-09:13:04] [TRT] [E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::3873] Error Code 10: Internal Error (Could not find any implementation for node Conv_74 + PWN(PWN(Sigmoid_75), Mul_76).)
Failed to building TRT engine!

这是为什么呢？ 我用的官方提供的模型转换的。（Why is that? I used the officially provided model conversion.）

**Comment by jws92** [comment]
Hi,
Would you please let me know your environment for conversion of TensorRT?

I didn't encounter any errors when I converted the official weights (yolov8n-seg.pt) of YOLOv8 to TensorRT engine, by using the codes in this repo.

By the way, converting PyTorch to ONNX generated an error because the version of YOLOv8 has been updated to 8.2.x.
Thus I modified the codes by specifying ONNX opset version as 12 in `export_onnx.py` as follows:
```python
model.export(format='onnx', 
             imgsz=args.imgsz, 
             half=True, 
             simplify=True, 
             workspace=4,
             opset=12)    # specify the ONNX opset version here
```
If you already have any errors in the ONNX conversion step, please try to use the code above.

**Comment by LijialinHub** [comment]
> ```python
> format='onnx', 
>              imgsz=args.imgsz, 
>              half=True, 
>              simplify=True, 
>              workspace=4,
>              opset=12
> ```

I used a new version and the error is still the same

**Comment by LijialinHub** [comment]
> > ```python
> > format='onnx', 
> >              imgsz=args.imgsz, 
> >              half=True, 
> >              simplify=True, 
> >              workspace=4,
> >              opset=12
> > ```
> 
> I used a new version and the error is still the same我使用了新版本，错误仍然是一样的
I do not know what the problem is, I tried to analyze the error with chatgpt, which probably means that there is no supported operator

**Comment by jws92** [comment]
When I conducted the experiments with `Dockerfile` provided by this repo, I was not able to reproduce your error.
So, what the environments do you use? Could you let me know your development environments?
If you did not use the `Dockerfile`, please try to your experiment in the environments built from `Dockerfile`.

**Comment by LijialinHub** [comment]
> When I conducted the experiments with `Dockerfile` provided by this repo, I was not able to reproduce your error.当我用这个repo提供的 `Dockerfile` 进行实验时，我无法重现你的错误。 So, what the environments do you use? Could you let me know your development environments? 那么，你使用的环境是什么？你能告诉我你的开发环境吗？ If you did not use the `Dockerfile`, please try to your experiment in the environments built from `Dockerfile`. 如果您没有使用 `Dockerfile` ，请尝试在从 `Dockerfile` 构建的环境中进行实验。



> When I conducted the experiments with `Dockerfile` provided by this repo, I was not able to reproduce your error.当我用这个repo提供的 `Dockerfile` 进行实验时，我无法重现你的错误。 So, what the environments do you use? Could you let me know your development environments? 那么，你使用的环境是什么？你能告诉我你的开发环境吗？ If you did not use the `Dockerfile`, please try to your experiment in the environments built from `Dockerfile`. 如果您没有使用 `Dockerfile` ，请尝试在从 `Dockerfile` 构建的环境中进行实验。

Since I was developing under windows, I didn't choose to use docker. I am cuda11.6,TensorRT-8.6.0.12. Could you please take a look at this version? Thank you for your patience。（因为我是在windows下开发 ，所以没用选择用docker 我是cuda11.6 ,TensorRT-8.6.0.12 . 请您看看这样的版本搭配可以吗？谢谢您的耐心）

**Comment by jws92** [comment]
My development environment is under Ubuntu 20.04 in WSL2 (Windows Subsystem for Linux), 
so I am sorry that I don't know how to convert the TensorRT engine in the raw Windows environments.
I think there may be some incompatibilities of the frameworks between Ubuntu and Windows, so the unexpected errors occurred.

Thus I recommend you use `Docker` in Windows system, or Ubuntu in WSL2, otherwise.
Once you build the `Dockerfile`, you can check the frameworks' dependencies as follows:
- TensorRT: 8.2.5.1
- CUDA: 11.7
- PyTorch: 1.12
- OpenCV: 4.5.5
- PyCUDA: 2022.2.2

In my opinion, one of the clues for solving the problem may match each framework's version as above.

**Comment by LijialinHub** [comment]
> My development environment is under Ubuntu 20.04 in WSL2 (Windows Subsystem for Linux),我的开发环境是在WSL 2（Linux的Windows子系统）中的Ubuntu 20.04下， so I am sorry that I don't know how to convert the TensorRT engine in the raw Windows environments. 所以很抱歉，我不知道如何在原始Windows环境中转换TensorRT引擎。 I think there may be some incompatibilities of the frameworks between Ubuntu and Windows, so the unexpected errors occurred. 我认为Ubuntu和Windows之间的框架可能存在一些不兼容性，因此发生了意想不到的错误。
> 
> Thus I recommend you use `Docker` in Windows system, or Ubuntu in WSL2, otherwise.因此，我建议你在Windows系统中使用 `Docker` ，或者在WSL 2中使用Ubuntu。 Once you build the `Dockerfile`, you can check the frameworks' dependencies as follows: 一旦你构建了 `Dockerfile` ，你可以检查框架的依赖关系，如下所示：
> 
> * TensorRT: 8.2.5.1 TensorRT：www.example.com
> * CUDA: 11.7 CUDA：11.7
> * PyTorch: 1.12 PyTorch：1.12
> * OpenCV: 4.5.5 OpenCV：4.5.5
> * PyCUDA: 2022.2.2 PyCUDA：2022.2.2
> 
> In my opinion, one of the clues for solving the problem may match each framework's version as above.在我看来，解决问题的一个线索可能与上述每个框架的版本相匹配。

ok，thank you very much， i try once
